"""Add category column to challenge table

Revision ID: 16d76187b19d
Revises: e34ef6c68083
Create Date: 2025-07-31 01:33:12.526280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d76187b19d'
down_revision = 'e34ef6c68083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('participation_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('cash_prize_cents', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('min_team_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_team_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('additional_requirements', sa.Text(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('additional_requirements')
        batch_op.drop_column('max_team_size')
        batch_op.drop_column('min_team_size')
        batch_op.drop_column('cash_prize_cents')
        batch_op.drop_column('participation_type')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
