"""Add file_path to Submission

Revision ID: e34ef6c68083
Revises: 6f7fb3e32827
Create Date: 2025-07-29 00:52:18.171270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34ef6c68083'
down_revision = '6f7fb3e32827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
